//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStock.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAdjustment> TAdjustments { get; set; }
        public virtual DbSet<TCategory> TCategories { get; set; }
        public virtual DbSet<TInventory> TInventories { get; set; }
        public virtual DbSet<TInventoryAdjustment> TInventoryAdjustments { get; set; }
        public virtual DbSet<TOrder> TOrders { get; set; }
        public virtual DbSet<TOrderProduct> TOrderProducts { get; set; }
        public virtual DbSet<TPayment> TPayments { get; set; }
        public virtual DbSet<TProduct> TProducts { get; set; }
        public virtual DbSet<TProductLocation> TProductLocations { get; set; }
        public virtual DbSet<TRole> TRoles { get; set; }
        public virtual DbSet<TSupplier> TSuppliers { get; set; }
        public virtual DbSet<TUser> TUsers { get; set; }
    }
}
