//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAlert
    {
        public int intAlertID { get; set; }
        public string strAlert { get; set; }
        public System.DateTime dtmAlertDate { get; set; }
        public string strAlertType { get; set; }
    }
}
