//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOrder()
        {
            this.TOrderProducts = new HashSet<TOrderProduct>();
        }
    
        public int intOrderID { get; set; }
        public System.DateTime dtmOrderDate { get; set; }
        public int intUserID { get; set; }
        public int intPaymentID { get; set; }
        public int intSupplierID { get; set; }
    
        public virtual TPayment TPayment { get; set; }
        public virtual TSupplier TSupplier { get; set; }
        public virtual TUser TUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOrderProduct> TOrderProducts { get; set; }
    }
}
