//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProductPriceHistory
    {
        public int intProductPriceHistoryID { get; set; }
        public string strProductName { get; set; }
        public System.DateTime dtmPurchaseDate { get; set; }
        public string strUnitType { get; set; }
        public decimal monCostPerUnit { get; set; }
        public int intPurchaseAmt { get; set; }
        public int intUserID { get; set; }
        public int intSupplierID { get; set; }
    
        public virtual TSupplier TSupplier { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
