//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSupplier()
        {
            this.TProductPriceHistories = new HashSet<TProductPriceHistory>();
        }
    
        public int intSupplierID { get; set; }
        public string strCompanyName { get; set; }
        public string strContactFirstName { get; set; }
        public string strContactLastName { get; set; }
        public string strEmail { get; set; }
        public string strAddress1 { get; set; }
        public string strZip { get; set; }
        public string strPhoneNumber { get; set; }
        public string strURL { get; set; }
        public string strNotes { get; set; }
        public string strContactState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TProductPriceHistory> TProductPriceHistories { get; set; }
    }
}
