//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUser()
        {
            this.TProductPriceHistories = new HashSet<TProductPriceHistory>();
        }
    
        public int intUserID { get; set; }
        public string strFirstName { get; set; }
        public string strLastName { get; set; }
        public string strPhoneNumber { get; set; }
        public string strEmail { get; set; }
        public string strUserName { get; set; }
        public string userPassword { get; set; }
        public int intRoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TProductPriceHistory> TProductPriceHistories { get; set; }
        public virtual TRole TRole { get; set; }
    }
}
